// Static course data for client-side rendering (mirrors the DB seed data)

export interface CourseInfo {
  id: string;
  title: string;
  description: string;
  subject: string;
  difficulty: "Beginner" | "Intermediate" | "Advanced";
  emoji: string;
  isFree: boolean;
  totalLessons: number;
  estimatedHours: number;
  whatYouWillLearn: string[];
}

export interface LessonInfo {
  id: string;
  courseId: string;
  lessonNumber: number;
  title: string;
  description: string;
  estimatedMinutes: number;
}

export const COURSES: CourseInfo[] = [
  // FREE COURSES
  {
    id: "python-beginners",
    title: "Python for Complete Beginners",
    description: "Start your coding journey with Python — the world's most beginner-friendly programming language. Learn variables, loops, functions, and build your first programs.",
    subject: "Coding",
    difficulty: "Beginner",
    emoji: "\uD83D\uDC0D",
    isFree: true,
    totalLessons: 10,
    estimatedHours: 3,
    whatYouWillLearn: [
      "Write Python code from scratch with confidence",
      "Understand variables, loops, and conditionals",
      "Create reusable functions and handle errors",
      "Build a complete number guessing game project",
    ],
  },
  {
    id: "math-foundations",
    title: "Math Foundations",
    description: "Build a rock-solid foundation in mathematics. Cover arithmetic, fractions, decimals, basic algebra, and problem-solving strategies.",
    subject: "Math",
    difficulty: "Beginner",
    emoji: "\uD83D\uDD22",
    isFree: true,
    totalLessons: 8,
    estimatedHours: 2,
    whatYouWillLearn: [
      "Master arithmetic operations with speed and accuracy",
      "Work confidently with fractions, decimals, and percentages",
      "Solve basic algebra equations",
      "Apply math to real-world word problems",
    ],
  },
  {
    id: "english-writing-basics",
    title: "English Writing Basics",
    description: "Master the fundamentals of English writing — grammar, sentence structure, paragraphs, and clear communication.",
    subject: "English",
    difficulty: "Beginner",
    emoji: "\u270D\uFE0F",
    isFree: true,
    totalLessons: 6,
    estimatedHours: 1.5,
    whatYouWillLearn: [
      "Identify and use all parts of speech correctly",
      "Build clear, grammatically correct sentences",
      "Write well-structured paragraphs with strong topic sentences",
      "Compose a short essay with intro, body, and conclusion",
    ],
  },
  {
    id: "how-internet-works",
    title: "How the Internet Works",
    description: "Understand the technology behind the internet — from browsers and servers to DNS, HTTP, and how data travels the world.",
    subject: "Tech",
    difficulty: "Beginner",
    emoji: "\uD83C\uDF10",
    isFree: true,
    totalLessons: 5,
    estimatedHours: 1,
    whatYouWillLearn: [
      "Explain how the internet works in simple terms",
      "Understand the roles of browsers, servers, and DNS",
      "Know the difference between HTTP and HTTPS",
      "Describe how data packets travel across the globe",
    ],
  },
  {
    id: "personal-finance-101",
    title: "Personal Finance 101",
    description: "Learn essential money skills — budgeting, saving, investing basics, and how to make smart financial decisions.",
    subject: "Finance",
    difficulty: "Beginner",
    emoji: "\uD83D\uDCB0",
    isFree: true,
    totalLessons: 7,
    estimatedHours: 2,
    whatYouWillLearn: [
      "Create and stick to a personal budget",
      "Understand saving strategies and emergency funds",
      "Know the basics of investing in stocks and index funds",
      "Make smart financial decisions and avoid common traps",
    ],
  },
  {
    id: "study-skills",
    title: "Study Skills & Learning How to Learn",
    description: "Discover proven techniques for effective studying — active recall, spaced repetition, note-taking methods, and time management.",
    subject: "Life Skills",
    difficulty: "Beginner",
    emoji: "\uD83E\uDDE0",
    isFree: true,
    totalLessons: 6,
    estimatedHours: 1.5,
    whatYouWillLearn: [
      "Use active recall and spaced repetition to study smarter",
      "Take effective notes using proven methods",
      "Manage your time and beat procrastination",
      "Prepare for exams without last-minute cramming",
    ],
  },
  // PRO COURSES
  {
    id: "fullstack-web-dev",
    title: "Full Stack Web Development Roadmap",
    description: "A complete roadmap from HTML/CSS to React, Node.js, databases, and deployment. Build real projects along the way.",
    subject: "Coding",
    difficulty: "Intermediate",
    emoji: "\uD83D\uDE80",
    isFree: false,
    totalLessons: 20,
    estimatedHours: 10,
    whatYouWillLearn: [
      "Build responsive websites with HTML, CSS, and JavaScript",
      "Create dynamic UIs with React and manage application state",
      "Build REST APIs with Node.js and Express",
      "Deploy a full-stack app with a database to the cloud",
    ],
  },
  {
    id: "advanced-mathematics",
    title: "Advanced Mathematics",
    description: "Dive deep into calculus, linear algebra, statistics, and mathematical reasoning for advanced students and exam prep.",
    subject: "Math",
    difficulty: "Advanced",
    emoji: "\uD83D\uDCD0",
    isFree: false,
    totalLessons: 15,
    estimatedHours: 6,
    whatYouWillLearn: [
      "Understand limits, derivatives, and integrals (calculus)",
      "Work with vectors, matrices, and linear algebra",
      "Apply probability and statistics to real problems",
      "Develop mathematical reasoning and proof techniques",
    ],
  },
  {
    id: "data-science-ai",
    title: "Data Science & AI Fundamentals",
    description: "Learn data analysis, machine learning concepts, Python for data science, and understand how AI systems work.",
    subject: "Coding/AI",
    difficulty: "Intermediate",
    emoji: "\uD83E\uDD16",
    isFree: false,
    totalLessons: 18,
    estimatedHours: 8,
    whatYouWillLearn: [
      "Analyze data with Python, NumPy, and Pandas",
      "Create visualizations and perform exploratory data analysis",
      "Build and evaluate machine learning models",
      "Understand neural networks, NLP, and AI ethics",
    ],
  },
  {
    id: "public-speaking",
    title: "Public Speaking & Communication",
    description: "Build confidence in public speaking — structure speeches, manage anxiety, use body language, and communicate persuasively.",
    subject: "Life Skills",
    difficulty: "Intermediate",
    emoji: "\uD83C\uDFA4",
    isFree: false,
    totalLessons: 10,
    estimatedHours: 3,
    whatYouWillLearn: [
      "Overcome stage fright and speak with confidence",
      "Structure speeches that engage and persuade",
      "Use body language and vocal delivery effectively",
      "Handle Q&A sessions and think on your feet",
    ],
  },
  {
    id: "business-entrepreneurship",
    title: "Business & Entrepreneurship",
    description: "Learn business fundamentals — idea validation, marketing, finance, leadership, and how to launch your own venture.",
    subject: "Business",
    difficulty: "Intermediate",
    emoji: "\uD83D\uDCBC",
    isFree: false,
    totalLessons: 12,
    estimatedHours: 4,
    whatYouWillLearn: [
      "Find and validate a business idea that solves real problems",
      "Build a brand and attract your first customers",
      "Understand financial management and business models",
      "Create a pitch and present to investors",
    ],
  },
  {
    id: "exam-preparation",
    title: "IELTS/SAT Exam Preparation",
    description: "Comprehensive exam prep covering reading, writing, math, and test-taking strategies for IELTS and SAT exams.",
    subject: "English",
    difficulty: "Advanced",
    emoji: "\uD83D\uDCDD",
    isFree: false,
    totalLessons: 15,
    estimatedHours: 6,
    whatYouWillLearn: [
      "Master reading comprehension and speed reading techniques",
      "Write high-scoring essays with strong structure and style",
      "Tackle advanced math problems tested on the SAT",
      "Develop effective test-taking strategies and time management",
    ],
  },
];

export const LESSONS: Record<string, LessonInfo[]> = {
  "python-beginners": [
    { id: "python-beginners-1", courseId: "python-beginners", lessonNumber: 1, title: "What is Programming?", description: "Understanding what programming is and why Python is a great first language", estimatedMinutes: 15 },
    { id: "python-beginners-2", courseId: "python-beginners", lessonNumber: 2, title: "Setting Up Python", description: "Installing Python and writing your first Hello World program", estimatedMinutes: 15 },
    { id: "python-beginners-3", courseId: "python-beginners", lessonNumber: 3, title: "Variables and Data Types", description: "Storing data in variables — strings, numbers, and booleans", estimatedMinutes: 20 },
    { id: "python-beginners-4", courseId: "python-beginners", lessonNumber: 4, title: "Input and Output", description: "Getting user input and displaying output with print()", estimatedMinutes: 15 },
    { id: "python-beginners-5", courseId: "python-beginners", lessonNumber: 5, title: "Conditionals: If/Else", description: "Making decisions in your code with if, elif, and else", estimatedMinutes: 20 },
    { id: "python-beginners-6", courseId: "python-beginners", lessonNumber: 6, title: "Loops: For and While", description: "Repeating actions with for loops and while loops", estimatedMinutes: 20 },
    { id: "python-beginners-7", courseId: "python-beginners", lessonNumber: 7, title: "Lists and Dictionaries", description: "Storing collections of data with lists and dictionaries", estimatedMinutes: 20 },
    { id: "python-beginners-8", courseId: "python-beginners", lessonNumber: 8, title: "Functions", description: "Creating reusable blocks of code with functions", estimatedMinutes: 20 },
    { id: "python-beginners-9", courseId: "python-beginners", lessonNumber: 9, title: "Error Handling", description: "Understanding and handling errors gracefully with try/except", estimatedMinutes: 15 },
    { id: "python-beginners-10", courseId: "python-beginners", lessonNumber: 10, title: "Your First Project: Number Guessing Game", description: "Putting it all together to build a fun number guessing game", estimatedMinutes: 20 },
  ],
  "math-foundations": [
    { id: "math-foundations-1", courseId: "math-foundations", lessonNumber: 1, title: "Number Sense and Place Value", description: "Understanding how numbers work and their place values", estimatedMinutes: 15 },
    { id: "math-foundations-2", courseId: "math-foundations", lessonNumber: 2, title: "Addition and Subtraction Mastery", description: "Strategies for fast and accurate addition and subtraction", estimatedMinutes: 15 },
    { id: "math-foundations-3", courseId: "math-foundations", lessonNumber: 3, title: "Multiplication and Division", description: "Building fluency with multiplication tables and division", estimatedMinutes: 15 },
    { id: "math-foundations-4", courseId: "math-foundations", lessonNumber: 4, title: "Fractions Made Easy", description: "Understanding, comparing, and operating with fractions", estimatedMinutes: 15 },
    { id: "math-foundations-5", courseId: "math-foundations", lessonNumber: 5, title: "Decimals and Percentages", description: "Working with decimals and understanding percentages", estimatedMinutes: 15 },
    { id: "math-foundations-6", courseId: "math-foundations", lessonNumber: 6, title: "Introduction to Algebra", description: "Using letters for unknowns and solving simple equations", estimatedMinutes: 15 },
    { id: "math-foundations-7", courseId: "math-foundations", lessonNumber: 7, title: "Geometry Basics", description: "Shapes, angles, area, and perimeter fundamentals", estimatedMinutes: 15 },
    { id: "math-foundations-8", courseId: "math-foundations", lessonNumber: 8, title: "Problem Solving Strategies", description: "Applying math to real-world word problems", estimatedMinutes: 15 },
  ],
  "english-writing-basics": [
    { id: "english-writing-1", courseId: "english-writing-basics", lessonNumber: 1, title: "Parts of Speech", description: "Nouns, verbs, adjectives, adverbs — the building blocks of English", estimatedMinutes: 15 },
    { id: "english-writing-2", courseId: "english-writing-basics", lessonNumber: 2, title: "Sentence Structure", description: "Building clear, correct sentences with subjects, verbs, and objects", estimatedMinutes: 15 },
    { id: "english-writing-3", courseId: "english-writing-basics", lessonNumber: 3, title: "Punctuation and Grammar", description: "Commas, periods, apostrophes, and common grammar rules", estimatedMinutes: 15 },
    { id: "english-writing-4", courseId: "english-writing-basics", lessonNumber: 4, title: "Writing Paragraphs", description: "Topic sentences, supporting details, and paragraph structure", estimatedMinutes: 15 },
    { id: "english-writing-5", courseId: "english-writing-basics", lessonNumber: 5, title: "Common Mistakes to Avoid", description: "Their/there/they're, your/you're, and other frequent errors", estimatedMinutes: 15 },
    { id: "english-writing-6", courseId: "english-writing-basics", lessonNumber: 6, title: "Writing a Short Essay", description: "Putting it all together — introduction, body, and conclusion", estimatedMinutes: 15 },
  ],
  "how-internet-works": [
    { id: "internet-works-1", courseId: "how-internet-works", lessonNumber: 1, title: "What is the Internet?", description: "A simple explanation of what the internet actually is", estimatedMinutes: 12 },
    { id: "internet-works-2", courseId: "how-internet-works", lessonNumber: 2, title: "Browsers and Servers", description: "How your browser talks to servers to load web pages", estimatedMinutes: 12 },
    { id: "internet-works-3", courseId: "how-internet-works", lessonNumber: 3, title: "DNS: The Internet Phone Book", description: "How domain names get translated to IP addresses", estimatedMinutes: 12 },
    { id: "internet-works-4", courseId: "how-internet-works", lessonNumber: 4, title: "HTTP and HTTPS", description: "How data is sent and received securely on the web", estimatedMinutes: 12 },
    { id: "internet-works-5", courseId: "how-internet-works", lessonNumber: 5, title: "How Data Travels the World", description: "Packets, routers, and the physical infrastructure of the internet", estimatedMinutes: 12 },
  ],
  "personal-finance-101": [
    { id: "finance-101-1", courseId: "personal-finance-101", lessonNumber: 1, title: "Money Mindset", description: "Understanding your relationship with money and financial goals", estimatedMinutes: 15 },
    { id: "finance-101-2", courseId: "personal-finance-101", lessonNumber: 2, title: "Budgeting Basics", description: "Creating a simple budget that actually works", estimatedMinutes: 20 },
    { id: "finance-101-3", courseId: "personal-finance-101", lessonNumber: 3, title: "Saving Strategies", description: "Emergency funds, saving goals, and the pay-yourself-first rule", estimatedMinutes: 15 },
    { id: "finance-101-4", courseId: "personal-finance-101", lessonNumber: 4, title: "Understanding Debt", description: "Good debt vs bad debt, interest rates, and paying off debt", estimatedMinutes: 15 },
    { id: "finance-101-5", courseId: "personal-finance-101", lessonNumber: 5, title: "Investing for Beginners", description: "Stocks, bonds, index funds — the basics of growing your money", estimatedMinutes: 20 },
    { id: "finance-101-6", courseId: "personal-finance-101", lessonNumber: 6, title: "Banking and Credit Scores", description: "How banks work, credit scores, and why they matter", estimatedMinutes: 15 },
    { id: "finance-101-7", courseId: "personal-finance-101", lessonNumber: 7, title: "Smart Financial Decisions", description: "Avoiding scams, impulse buying, and making money work for you", estimatedMinutes: 15 },
  ],
  "study-skills": [
    { id: "study-skills-1", courseId: "study-skills", lessonNumber: 1, title: "How Your Brain Learns", description: "Understanding memory, focus, and how learning actually works", estimatedMinutes: 15 },
    { id: "study-skills-2", courseId: "study-skills", lessonNumber: 2, title: "Active Recall", description: "The most powerful study technique — test yourself to remember better", estimatedMinutes: 15 },
    { id: "study-skills-3", courseId: "study-skills", lessonNumber: 3, title: "Spaced Repetition", description: "Why timing matters and how to space out your studying", estimatedMinutes: 15 },
    { id: "study-skills-4", courseId: "study-skills", lessonNumber: 4, title: "Note-Taking Methods", description: "Cornell method, mind maps, and effective note-taking strategies", estimatedMinutes: 15 },
    { id: "study-skills-5", courseId: "study-skills", lessonNumber: 5, title: "Time Management for Students", description: "Pomodoro technique, scheduling, and beating procrastination", estimatedMinutes: 15 },
    { id: "study-skills-6", courseId: "study-skills", lessonNumber: 6, title: "Exam Preparation Strategies", description: "How to prepare for exams effectively without cramming", estimatedMinutes: 15 },
  ],
  "fullstack-web-dev": [
    { id: "fullstack-1", courseId: "fullstack-web-dev", lessonNumber: 1, title: "Web Development Overview", description: "Understanding frontend, backend, and how they work together", estimatedMinutes: 25 },
    { id: "fullstack-2", courseId: "fullstack-web-dev", lessonNumber: 2, title: "HTML Fundamentals", description: "Building the structure of web pages with HTML", estimatedMinutes: 30 },
    { id: "fullstack-3", courseId: "fullstack-web-dev", lessonNumber: 3, title: "CSS Styling", description: "Making web pages beautiful with CSS", estimatedMinutes: 30 },
    { id: "fullstack-4", courseId: "fullstack-web-dev", lessonNumber: 4, title: "Responsive Design", description: "Making websites work on all screen sizes", estimatedMinutes: 30 },
    { id: "fullstack-5", courseId: "fullstack-web-dev", lessonNumber: 5, title: "JavaScript Basics", description: "Adding interactivity with JavaScript fundamentals", estimatedMinutes: 30 },
    { id: "fullstack-6", courseId: "fullstack-web-dev", lessonNumber: 6, title: "JavaScript DOM Manipulation", description: "Dynamically changing web pages with JavaScript", estimatedMinutes: 30 },
    { id: "fullstack-7", courseId: "fullstack-web-dev", lessonNumber: 7, title: "Modern JavaScript (ES6+)", description: "Arrow functions, destructuring, modules, and more", estimatedMinutes: 30 },
    { id: "fullstack-8", courseId: "fullstack-web-dev", lessonNumber: 8, title: "React Fundamentals", description: "Building UIs with React components and JSX", estimatedMinutes: 30 },
    { id: "fullstack-9", courseId: "fullstack-web-dev", lessonNumber: 9, title: "React State and Props", description: "Managing data flow in React applications", estimatedMinutes: 30 },
    { id: "fullstack-10", courseId: "fullstack-web-dev", lessonNumber: 10, title: "React Hooks and Effects", description: "useState, useEffect, and custom hooks", estimatedMinutes: 30 },
    { id: "fullstack-11", courseId: "fullstack-web-dev", lessonNumber: 11, title: "Routing and Navigation", description: "Single page applications with React Router", estimatedMinutes: 30 },
    { id: "fullstack-12", courseId: "fullstack-web-dev", lessonNumber: 12, title: "Node.js Introduction", description: "Server-side JavaScript with Node.js", estimatedMinutes: 30 },
    { id: "fullstack-13", courseId: "fullstack-web-dev", lessonNumber: 13, title: "Express.js and REST APIs", description: "Building APIs with Express.js", estimatedMinutes: 30 },
    { id: "fullstack-14", courseId: "fullstack-web-dev", lessonNumber: 14, title: "Databases: SQL Basics", description: "Storing data with PostgreSQL and SQL queries", estimatedMinutes: 30 },
    { id: "fullstack-15", courseId: "fullstack-web-dev", lessonNumber: 15, title: "Database Integration", description: "Connecting your API to a database", estimatedMinutes: 30 },
    { id: "fullstack-16", courseId: "fullstack-web-dev", lessonNumber: 16, title: "Authentication and Security", description: "User login, JWT tokens, and security best practices", estimatedMinutes: 30 },
    { id: "fullstack-17", courseId: "fullstack-web-dev", lessonNumber: 17, title: "File Uploads and Storage", description: "Handling file uploads and cloud storage", estimatedMinutes: 30 },
    { id: "fullstack-18", courseId: "fullstack-web-dev", lessonNumber: 18, title: "Testing Your Application", description: "Unit tests, integration tests, and test-driven development", estimatedMinutes: 30 },
    { id: "fullstack-19", courseId: "fullstack-web-dev", lessonNumber: 19, title: "Deployment", description: "Deploying your full stack application to the cloud", estimatedMinutes: 30 },
    { id: "fullstack-20", courseId: "fullstack-web-dev", lessonNumber: 20, title: "Final Project: Build a Full Stack App", description: "Putting it all together in a capstone project", estimatedMinutes: 45 },
  ],
  "advanced-mathematics": [
    { id: "adv-math-1", courseId: "advanced-mathematics", lessonNumber: 1, title: "Functions and Graphs", description: "Understanding functions, domains, ranges, and graphing", estimatedMinutes: 25 },
    { id: "adv-math-2", courseId: "advanced-mathematics", lessonNumber: 2, title: "Limits and Continuity", description: "The foundation of calculus — understanding limits", estimatedMinutes: 25 },
    { id: "adv-math-3", courseId: "advanced-mathematics", lessonNumber: 3, title: "Introduction to Derivatives", description: "Rates of change and the concept of differentiation", estimatedMinutes: 25 },
    { id: "adv-math-4", courseId: "advanced-mathematics", lessonNumber: 4, title: "Derivative Rules and Applications", description: "Power rule, chain rule, and practical applications", estimatedMinutes: 25 },
    { id: "adv-math-5", courseId: "advanced-mathematics", lessonNumber: 5, title: "Introduction to Integrals", description: "Area under curves and the concept of integration", estimatedMinutes: 25 },
    { id: "adv-math-6", courseId: "advanced-mathematics", lessonNumber: 6, title: "Integration Techniques", description: "Substitution, parts, and other integration methods", estimatedMinutes: 25 },
    { id: "adv-math-7", courseId: "advanced-mathematics", lessonNumber: 7, title: "Sequences and Series", description: "Arithmetic, geometric sequences, and convergence", estimatedMinutes: 25 },
    { id: "adv-math-8", courseId: "advanced-mathematics", lessonNumber: 8, title: "Vectors and Matrices", description: "Introduction to linear algebra concepts", estimatedMinutes: 25 },
    { id: "adv-math-9", courseId: "advanced-mathematics", lessonNumber: 9, title: "Matrix Operations", description: "Multiplication, inverses, and determinants", estimatedMinutes: 25 },
    { id: "adv-math-10", courseId: "advanced-mathematics", lessonNumber: 10, title: "Systems of Equations", description: "Solving systems using matrices and elimination", estimatedMinutes: 25 },
    { id: "adv-math-11", courseId: "advanced-mathematics", lessonNumber: 11, title: "Probability Fundamentals", description: "Events, sample spaces, and probability rules", estimatedMinutes: 25 },
    { id: "adv-math-12", courseId: "advanced-mathematics", lessonNumber: 12, title: "Statistics and Distributions", description: "Mean, median, standard deviation, and normal distribution", estimatedMinutes: 25 },
    { id: "adv-math-13", courseId: "advanced-mathematics", lessonNumber: 13, title: "Hypothesis Testing", description: "Statistical tests and drawing conclusions from data", estimatedMinutes: 25 },
    { id: "adv-math-14", courseId: "advanced-mathematics", lessonNumber: 14, title: "Trigonometry Deep Dive", description: "Trig functions, identities, and applications", estimatedMinutes: 25 },
    { id: "adv-math-15", courseId: "advanced-mathematics", lessonNumber: 15, title: "Mathematical Proofs and Reasoning", description: "Logic, proof techniques, and mathematical thinking", estimatedMinutes: 25 },
  ],
  "data-science-ai": [
    { id: "ds-ai-1", courseId: "data-science-ai", lessonNumber: 1, title: "What is Data Science?", description: "Overview of the data science field and its applications", estimatedMinutes: 25 },
    { id: "ds-ai-2", courseId: "data-science-ai", lessonNumber: 2, title: "Python for Data Science", description: "Setting up your data science toolkit with Python", estimatedMinutes: 25 },
    { id: "ds-ai-3", courseId: "data-science-ai", lessonNumber: 3, title: "Working with NumPy", description: "Numerical computing with NumPy arrays", estimatedMinutes: 25 },
    { id: "ds-ai-4", courseId: "data-science-ai", lessonNumber: 4, title: "Data Analysis with Pandas", description: "Loading, cleaning, and analyzing data with Pandas", estimatedMinutes: 30 },
    { id: "ds-ai-5", courseId: "data-science-ai", lessonNumber: 5, title: "Data Visualization", description: "Creating charts and graphs with Matplotlib and Seaborn", estimatedMinutes: 25 },
    { id: "ds-ai-6", courseId: "data-science-ai", lessonNumber: 6, title: "Exploratory Data Analysis", description: "Techniques for understanding and exploring datasets", estimatedMinutes: 25 },
    { id: "ds-ai-7", courseId: "data-science-ai", lessonNumber: 7, title: "Statistics for Data Science", description: "Essential statistical concepts for data analysis", estimatedMinutes: 25 },
    { id: "ds-ai-8", courseId: "data-science-ai", lessonNumber: 8, title: "Introduction to Machine Learning", description: "What is ML and how machines learn from data", estimatedMinutes: 25 },
    { id: "ds-ai-9", courseId: "data-science-ai", lessonNumber: 9, title: "Supervised Learning: Regression", description: "Predicting numerical values with regression models", estimatedMinutes: 30 },
    { id: "ds-ai-10", courseId: "data-science-ai", lessonNumber: 10, title: "Supervised Learning: Classification", description: "Categorizing data with classification algorithms", estimatedMinutes: 30 },
    { id: "ds-ai-11", courseId: "data-science-ai", lessonNumber: 11, title: "Unsupervised Learning", description: "Clustering, dimensionality reduction, and pattern discovery", estimatedMinutes: 25 },
    { id: "ds-ai-12", courseId: "data-science-ai", lessonNumber: 12, title: "Model Evaluation", description: "Accuracy, precision, recall, and choosing the right metrics", estimatedMinutes: 25 },
    { id: "ds-ai-13", courseId: "data-science-ai", lessonNumber: 13, title: "Feature Engineering", description: "Creating and selecting the right features for models", estimatedMinutes: 25 },
    { id: "ds-ai-14", courseId: "data-science-ai", lessonNumber: 14, title: "Neural Networks Basics", description: "Understanding how neural networks work", estimatedMinutes: 30 },
    { id: "ds-ai-15", courseId: "data-science-ai", lessonNumber: 15, title: "Deep Learning Overview", description: "CNNs, RNNs, and modern deep learning architectures", estimatedMinutes: 25 },
    { id: "ds-ai-16", courseId: "data-science-ai", lessonNumber: 16, title: "Natural Language Processing", description: "Teaching machines to understand human language", estimatedMinutes: 25 },
    { id: "ds-ai-17", courseId: "data-science-ai", lessonNumber: 17, title: "AI Ethics and Bias", description: "Responsible AI — fairness, bias, and ethical considerations", estimatedMinutes: 25 },
    { id: "ds-ai-18", courseId: "data-science-ai", lessonNumber: 18, title: "Building an End-to-End ML Project", description: "From data collection to deployment — a complete project", estimatedMinutes: 35 },
  ],
  "public-speaking": [
    { id: "speaking-1", courseId: "public-speaking", lessonNumber: 1, title: "Overcoming the Fear of Speaking", description: "Understanding stage fright and techniques to manage anxiety", estimatedMinutes: 15 },
    { id: "speaking-2", courseId: "public-speaking", lessonNumber: 2, title: "Structuring Your Message", description: "How to organize a talk with a clear beginning, middle, and end", estimatedMinutes: 20 },
    { id: "speaking-3", courseId: "public-speaking", lessonNumber: 3, title: "The Power of Storytelling", description: "Using stories to engage and persuade your audience", estimatedMinutes: 15 },
    { id: "speaking-4", courseId: "public-speaking", lessonNumber: 4, title: "Body Language and Presence", description: "How your posture, gestures, and eye contact affect your message", estimatedMinutes: 20 },
    { id: "speaking-5", courseId: "public-speaking", lessonNumber: 5, title: "Voice and Delivery", description: "Pace, tone, volume, and pauses — mastering vocal delivery", estimatedMinutes: 15 },
    { id: "speaking-6", courseId: "public-speaking", lessonNumber: 6, title: "Visual Aids and Slides", description: "Creating effective presentations that support your message", estimatedMinutes: 20 },
    { id: "speaking-7", courseId: "public-speaking", lessonNumber: 7, title: "Handling Q&A Sessions", description: "Answering questions confidently and thinking on your feet", estimatedMinutes: 15 },
    { id: "speaking-8", courseId: "public-speaking", lessonNumber: 8, title: "Persuasive Communication", description: "Techniques for influencing and persuading your audience", estimatedMinutes: 20 },
    { id: "speaking-9", courseId: "public-speaking", lessonNumber: 9, title: "Virtual Presentations", description: "Speaking effectively in online meetings and webinars", estimatedMinutes: 15 },
    { id: "speaking-10", courseId: "public-speaking", lessonNumber: 10, title: "Your Signature Talk", description: "Creating and delivering your own signature presentation", estimatedMinutes: 25 },
  ],
  "business-entrepreneurship": [
    { id: "business-1", courseId: "business-entrepreneurship", lessonNumber: 1, title: "The Entrepreneurial Mindset", description: "What makes entrepreneurs different and how to think like one", estimatedMinutes: 20 },
    { id: "business-2", courseId: "business-entrepreneurship", lessonNumber: 2, title: "Finding a Business Idea", description: "Identifying problems worth solving and validating ideas", estimatedMinutes: 20 },
    { id: "business-3", courseId: "business-entrepreneurship", lessonNumber: 3, title: "Market Research", description: "Understanding your target market and competition", estimatedMinutes: 20 },
    { id: "business-4", courseId: "business-entrepreneurship", lessonNumber: 4, title: "Business Models", description: "How businesses make money — different business model types", estimatedMinutes: 20 },
    { id: "business-5", courseId: "business-entrepreneurship", lessonNumber: 5, title: "Building a Brand", description: "Creating a brand identity that resonates with customers", estimatedMinutes: 20 },
    { id: "business-6", courseId: "business-entrepreneurship", lessonNumber: 6, title: "Marketing Fundamentals", description: "Digital marketing, social media, and getting your first customers", estimatedMinutes: 20 },
    { id: "business-7", courseId: "business-entrepreneurship", lessonNumber: 7, title: "Sales and Customer Relations", description: "Selling your product and building lasting customer relationships", estimatedMinutes: 20 },
    { id: "business-8", courseId: "business-entrepreneurship", lessonNumber: 8, title: "Financial Management", description: "Revenue, expenses, profit margins, and financial planning", estimatedMinutes: 20 },
    { id: "business-9", courseId: "business-entrepreneurship", lessonNumber: 9, title: "Building a Team", description: "Hiring, leadership, and creating a great company culture", estimatedMinutes: 20 },
    { id: "business-10", courseId: "business-entrepreneurship", lessonNumber: 10, title: "Pitching Your Idea", description: "Creating a compelling pitch deck and presenting to investors", estimatedMinutes: 20 },
    { id: "business-11", courseId: "business-entrepreneurship", lessonNumber: 11, title: "Legal Basics", description: "Business structures, contracts, and protecting your business", estimatedMinutes: 20 },
    { id: "business-12", courseId: "business-entrepreneurship", lessonNumber: 12, title: "Scaling Your Business", description: "Growth strategies, systems, and taking your business to the next level", estimatedMinutes: 20 },
  ],
  "exam-preparation": [
    { id: "exam-prep-1", courseId: "exam-preparation", lessonNumber: 1, title: "Understanding the Exam Format", description: "Overview of IELTS and SAT structure, scoring, and what to expect", estimatedMinutes: 20 },
    { id: "exam-prep-2", courseId: "exam-preparation", lessonNumber: 2, title: "Reading Comprehension Strategies", description: "Speed reading, skimming, scanning, and answering techniques", estimatedMinutes: 25 },
    { id: "exam-prep-3", courseId: "exam-preparation", lessonNumber: 3, title: "Advanced Reading Practice", description: "Tackling complex passages and inference questions", estimatedMinutes: 25 },
    { id: "exam-prep-4", courseId: "exam-preparation", lessonNumber: 4, title: "Writing: Essay Structure", description: "Planning and structuring high-scoring essays", estimatedMinutes: 25 },
    { id: "exam-prep-5", courseId: "exam-preparation", lessonNumber: 5, title: "Writing: Argument and Analysis", description: "Building persuasive arguments and analyzing evidence", estimatedMinutes: 25 },
    { id: "exam-prep-6", courseId: "exam-preparation", lessonNumber: 6, title: "Writing: Grammar and Style", description: "Advanced grammar, vocabulary, and writing style for exams", estimatedMinutes: 25 },
    { id: "exam-prep-7", courseId: "exam-preparation", lessonNumber: 7, title: "SAT Math: Algebra and Functions", description: "Core algebra concepts tested on the SAT", estimatedMinutes: 25 },
    { id: "exam-prep-8", courseId: "exam-preparation", lessonNumber: 8, title: "SAT Math: Advanced Topics", description: "Geometry, trigonometry, and complex problem-solving", estimatedMinutes: 25 },
    { id: "exam-prep-9", courseId: "exam-preparation", lessonNumber: 9, title: "SAT Math: Data Analysis", description: "Statistics, probability, and data interpretation", estimatedMinutes: 25 },
    { id: "exam-prep-10", courseId: "exam-preparation", lessonNumber: 10, title: "IELTS Listening Skills", description: "Strategies for the IELTS listening section", estimatedMinutes: 25 },
    { id: "exam-prep-11", courseId: "exam-preparation", lessonNumber: 11, title: "IELTS Speaking Practice", description: "Fluency, coherence, and speaking test techniques", estimatedMinutes: 25 },
    { id: "exam-prep-12", courseId: "exam-preparation", lessonNumber: 12, title: "Vocabulary Building", description: "Essential vocabulary for high exam scores", estimatedMinutes: 25 },
    { id: "exam-prep-13", courseId: "exam-preparation", lessonNumber: 13, title: "Time Management in Exams", description: "Pacing yourself and managing time during the test", estimatedMinutes: 25 },
    { id: "exam-prep-14", courseId: "exam-preparation", lessonNumber: 14, title: "Practice Test Strategies", description: "How to use practice tests effectively for maximum improvement", estimatedMinutes: 25 },
    { id: "exam-prep-15", courseId: "exam-preparation", lessonNumber: 15, title: "Final Review and Exam Day Tips", description: "Last-minute review strategies and what to do on exam day", estimatedMinutes: 25 },
  ],
};
